FROM registry.qy.t9kcloud.cn/topsrider/jupyterlab-torch-2.3.0:20241224

ENV HF_ENDPOINT=https://hf-mirror.com

RUN pip install --no-cache-dir --upgrade pip && \
pip install --no-cache-dir fastmcp==2.8.1

WORKDIR /app
COPY . .
EXPOSE 8000

ENTRYPOINT ["python", "server.py"]
