apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-law-searcher-sse
  labels:
    app: mcp-server-law-searcher-sse
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-law-searcher-sse
      version: v1
  template:
    metadata:
      labels:
        app: mcp-server-law-searcher-sse
        version: v1
    spec:
      containers:
      - name: mcp-server-law-searcher-sse
        image: registry.qy.t9kcloud.cn/topsrider/mcp-server:law-searcher-20250716
        imagePullPolicy: Always
        args: ["--sse"]
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: mcp-server-law-searcher-sse-config
        livenessProbe:
          httpGet:
            path: /mcp/law-searcher/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /mcp/law-searcher/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: 4Gi
            cpu: 2
            enflame.com/gcu: "1"
          limits:
            memory: 8Gi
            cpu: 4
            enflame.com/gcu: "1"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 

---

apiVersion: v1
kind: Service
metadata:
  name: mcp-server-law-searcher-sse-service
  labels:
    app: mcp-server-law-searcher-sse
spec:
  selector:
    app: mcp-server-law-searcher-sse
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mcp-server-law-searcher-sse-vs
spec:
  hosts:
  - '*'
  gateways:
  - project-gateway
  http:
  - match:
    - uri:
        prefix: /mcp/law-searcher-sse/
    rewrite:
      uri: /mcp/law-searcher-sse/
    route:
    - destination:
        host: mcp-server-law-searcher-sse-service
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-law-searcher-sse-config
data:
  MILVUS_URI: "http://app-milvus-xxxxxxxx.demo.svc.cluster.local:19530"
  MILVUS_TOKEN: "root:Milvus"
  MILVUS_DB: "default"
  MILVUS_COLLECTION_CRIMINAL_LAW: "criminal_law"
  MILVUS_COLLECTION_CIVIL_CODE: "civil_code"
  EMBEDDING_BASE_URL: "http://app-vllm-enflame-xxxxxxxx.demo.ksvc.qy.t9kcloud.cn/v1"
  EMBEDDING_MODEL: "Qwen3-Embedding-0.6B"
  ENABLE_AUTH: "false"
