[project]
name = "mcp-reranker"
version = "0.1.0"
description = "MCP Reranker Server - 基于搜索结果的重排序服务"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.8.1",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "uvicorn>=0.24.0",
]
