image:
  repository: "registry.cn-hangzhou.aliyuncs.com/t9k/open-webui"
  tag: "v0.6.25-law-qa"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 4Gi

persistence:
  size: 2Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  existingClaim: ""

pipelines:
  enabled: false
  extraEnvVars: []
  image:
    registry: "$(T9K_APP_IMAGE_REGISTRY)"
    repository: "$(T9K_APP_IMAGE_NAMESPACE)/pipelines"
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 4
      memory: 8Gi

extraEnvVars: []
