apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-law-searcher
  labels:
    app: mcp-server-law-searcher
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-law-searcher
      version: v1
  template:
    metadata:
      labels:
        app: mcp-server-law-searcher
        version: v1
    spec:
      containers:
      - name: mcp-server-law-searcher
        image: registry.cn-hangzhou.aliyuncs.com/t9k/mcp-server:law-searcher-20250912
        # image: registry.qy.t9kcloud.cn/topsrider/mcp-server:law-searcher-20250904
        imagePullPolicy: Always
        # args: ["--sse"]
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: mcp-server-law-searcher-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: 4Gi
            cpu: 2
            nvidia.com/gpu: 1
            # enflame.com/gcu: 1
          limits:
            memory: 8Gi
            cpu: 4
            nvidia.com/gpu: 1
            # enflame.com/gcu: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 

---

apiVersion: v1
kind: Service
metadata:
  name: mcp-server-law-searcher-service
  labels:
    app: mcp-server-law-searcher
spec:
  selector:
    app: mcp-server-law-searcher
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mcp-server-law-searcher-vs
spec:
  hosts:
  - '*'
  gateways:
  - project-gateway
  http:
  - match:
    - uri:
        prefix: /mcp/law-searcher/
    rewrite:
      uri: /
    route:
    - destination:
        host: mcp-server-law-searcher-service
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-law-searcher-config
data:
  MILVUS_URI: "http://app-milvus-xxxxxxxx.demo.svc.cluster.local:19530"
  MILVUS_TOKEN: "root:Milvus"
  MILVUS_DB: "default"
  MILVUS_COLLECTION: "cn_law"
  EMBEDDING_BASE_URL: "http://app-vllm-enflame-xxxxxxxx.demo.ksvc.qy.t9kcloud.cn/v1"
  EMBEDDING_MODEL: "Qwen3-Embedding-0.6B"
  ENABLE_AUTH: "false"
