apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-reranker
  labels:
    app: mcp-server-reranker
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-reranker
      version: v1
  template:
    metadata:
      labels:
        app: mcp-server-reranker
        version: v1
    spec:
      containers:
      - name: mcp-server-reranker
        image: registry.qy.t9kcloud.cn/topsrider/mcp-server:reranker-20250627
        imagePullPolicy: Always
        # args: ["--sse"]
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: mcp-server-reranker-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: 4Gi
            cpu: 2
            enflame.com/gcu: "1"
          limits:
            memory: 8Gi
            cpu: 4
            enflame.com/gcu: "1"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 

---

apiVersion: v1
kind: Service
metadata:
  name: mcp-server-reranker-service
  labels:
    app: mcp-server-reranker
spec:
  selector:
    app: mcp-server-reranker
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mcp-server-reranker-vs
spec:
  hosts:
  - '*'
  gateways:
  - project-gateway
  http:
  - match:
    - uri:
        prefix: /mcp/reranker/
    rewrite:
      uri: /
    route:
    - destination:
        host: mcp-server-reranker-service
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-reranker-config
data:
  RERANKER_BASE_URL: "http://app-vllm-enflame-xxxxxxxx.demo.ksvc.qy.t9kcloud.cn"
  RERANKER_MODEL: "bge-reranker-v2-m3"
  ENABLE_AUTH: "false"
